export const DO_SEARCH = 'DO_SEARCH'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const CREATE = 'CREATE'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const NUMBER_ITEMS = 'NUMBER_ITEMS'
export const SWITCH_TAB = 'SWITCH_TAB'
